### ISSUE TITLE
HTTPS warnings

### ISSUE THREAD

**Issue by alanablett** [c3limited/magento2-environment-banner#1]
https://github.com/c3limited/magento2-environment-banner/blob/8b9edd7722a60092bbaa92d134a853a4f861e26a/view/adminhtml/templates/environment_text.phtml#L3

When loaded in a site using https, this reference to the font over http will cause the browser to squark about mixed content types. So I guess we need to change it to https, or if its not essential just use a system font and avoid another http request.

**Comment by maderlock** [comment]
Thanks for raising the issue. The aim of the module is to be lightweight so I've removed the need for the font. I agree it's not really needed.
